site_name: ML-OPF Benchmark
repo_url: https://github.com/XinyiLiu04/ml-opf-bench 
repo_name: GitHub (ml-opf-bench)  

# style
theme:
  name: material
  palette:
    primary: black
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - content.code.copy
  font:
    text: Roboto
    code: Fira Code

plugins:
  - search:          
  - table-reader:    

# LaTeX 
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:  
  - tables:                
  - attr_list:             

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# navigation bar
nav:
  - Overview: index.md
  - Experiments setup:
    - datasets: benchmark/datasets.md
    - metrics: benchmark/metrics.md
  - Bench Results:
    - Results: results/comparison.md
    - accuracy: results/accuracy.md
  - Code: resources.md
  - References: references.md
